#!/usr/bin/env python3
"""PS Points scoring engine — Peasant Smith.

Computes the composite PS Points score for benchmark records and generates
the leaderboard. Formula and rationale: docs/scoring.md.

Usage:
  compute_score.py score <file.json> [...]     # print/patch ps_points per record
  compute_score.py leaderboard                 # regenerate LEADERBOARD.md
  compute_score.py leaderboard --csv data/benchmarks.csv
"""
import argparse, csv, glob, json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def speed_points(median_tps):
    """10 points per t/s, capped at 100 t/s (1000 pts)."""
    if median_tps is None:
        return 0
    return min(median_tps, 100) * 10


def reliability_points(completed, attempted):
    """Up to 50 pts for completing the full suite."""
    if not attempted:
        return 0
    return 50 * (completed / attempted)


def latency_points(ttft_s):
    """TTFT bonus: <=1s: 50, <=3s: 30, <=10s: 10, else 0."""
    if ttft_s is None:
        return 0
    if ttft_s <= 1:
        return 50
    if ttft_s <= 3:
        return 30
    if ttft_s <= 10:
        return 10
    return 0


def context_points(ctx):
    """Long-context bonus: >=128k: 30, >=64k: 20, >=32k: 10."""
    if not ctx:
        return 0
    if ctx >= 131072:
        return 30
    if ctx >= 65536:
        return 20
    if ctx >= 32768:
        return 10
    return 0


def score_record(rec):
    perf = rec.get("performance", {})
    tests = rec.get("tests", {}) or {}
    tps = perf.get("generation_tokens_per_second")
    ttft = perf.get("time_to_first_token_seconds")
    ctx = (rec.get("configuration") or {}).get("context_size")
    total = (speed_points(tps)
             + reliability_points(tests.get("completed"), tests.get("attempted"))
             + latency_points(ttft)
             + context_points(ctx))
    return round(total, 1), {
        "speed": round(speed_points(tps), 1),
        "reliability": round(reliability_points(tests.get("completed"), tests.get("attempted")), 1),
        "latency": latency_points(ttft),
        "context": context_points(ctx),
    }


def load_raw_records():
    recs = []
    for path in sorted(glob.glob(os.path.join(REPO, "benchmarks", "raw", "*.json"))):
        try:
            rec = json.load(open(path))
        except json.JSONDecodeError as e:
            print(f"WARN: skipping unparseable {path}: {e}", file=sys.stderr)
            continue
        if rec.get("example"):
            continue
        rec["_path"] = path
        recs.append(rec)
    return recs


def load_csv_records(path):
    recs = []
    with open(path) as f:
        for row in csv.DictReader(f):
            if row.get("example") == "true":
                continue
            def num(k):
                try:
                    return float(row[k]) if row.get(k) not in (None, "") else None
                except ValueError:
                    return None
            done = (row.get("tests_completed") or "").split("/")
            recs.append({
                "benchmark_id": row["benchmark_id"],
                "model": {"model_name": row["model_name"],
                          "model_family": row.get("model_family") or ""},
                "performance": {
                    "generation_tokens_per_second": num("generation_tps_median"),
                    "generation_tps_max": num("generation_tps_max"),
                    "total_runtime_seconds": num("total_runtime_seconds"),
                },
                "configuration": {"context_size": int(num("context_size") or 0) or None},
                "tests": {"attempted": int(done[1]) if len(done) == 2 else None,
                          "completed": int(done[0]) if len(done) == 2 else None},
                "result_classification": row.get("result_classification"),
                "run_date": row.get("run_date"),
                "gpu_name": row.get("gpu_name"),
                "gpu_count": row.get("gpu_count"),
                "inference_backend": row.get("inference_backend"),
            })
    return recs


def render_leaderboard(recs):
    scored = []
    for rec in recs:
        total, parts = score_record(rec)
        scored.append((total, parts, rec))
    scored.sort(key=lambda x: -x[0])

    lines = []
    lines.append("# Peasant Smith Leaderboard")
    lines.append("")
    lines.append("*Auto-generated by `scripts/score/compute_score.py leaderboard` — do not edit by hand.*")
    lines.append("")
    lines.append("Scoring formula: [docs/scoring.md](docs/scoring.md) · "
                 "Protocols: [docs/tests.md](docs/tests.md) · "
                 f"Records: {len(scored)}")
    lines.append("")
    lines.append("## Run leaderboard")
    lines.append("")
    lines.append("| # | ID | Model | Quant | t/s (median) | Tests | Class | PS Points |")
    lines.append("|---|----|-------|-------|--------------|-------|-------|-----------|")
    for i, (total, parts, rec) in enumerate(scored, 1):
        m = rec.get("model", {})
        perf = rec.get("performance", {})
        t = rec.get("tests", {}) or {}
        tests = f"{t.get('completed')}/{t.get('attempted')}" if t.get("attempted") else "—"
        cls = rec.get("result_classification", "—")
        tps = perf.get("generation_tokens_per_second")
        lines.append(
            f"| {i} | {rec.get('benchmark_id') or '—'} | "
            f"{m.get('model_name', '?')} | {m.get('quantization') or '—'} | "
            f"{tps if tps is not None else '—'} | {tests} | {cls} | **{total:.0f}** |")
    lines.append("")

    # per-model best
    best = {}
    for total, parts, rec in scored:
        name = rec.get("model", {}).get("model_name", "?")
        if name not in best:
            best[name] = (total, rec)
    lines.append("## Best score per model")
    lines.append("")
    lines.append("| Model | Best run | PS Points | t/s |")
    lines.append("|-------|----------|-----------|-----|")
    for name, (total, rec) in sorted(best.items(), key=lambda kv: -kv[1][0]):
        tps = rec.get("performance", {}).get("generation_tokens_per_second")
        lines.append(f"| {name} | {rec.get('benchmark_id') or '—'} | **{total:.0f}** | "
                     f"{tps if tps is not None else '—'} |")
    lines.append("")
    lines.append("---")
    lines.append("*Peasant Smith — making new AI run on old hardware. "
                 "Data license: CC BY 4.0.*")
    lines.append("")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description="PS Points scoring engine")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("score", help="compute/patch ps_points on raw JSON records").add_argument(
        "files", nargs="*", help="JSON files (default: all raw records)")
    lb = sub.add_parser("leaderboard", help="regenerate LEADERBOARD.md")
    lb.add_argument("--csv", default=None, help="source CSV instead of raw JSON")
    lb.add_argument("--patch-score", action="store_true", help=argparse.SUPPRESS)
    args = p.parse_args()
    if args.cmd == "score":
        args.patch = True

    if args.cmd == "score":
        paths = args.files or [r["_path"] for r in load_raw_records()]
        for path in paths:
            rec = json.load(open(path))
            total, parts = score_record(rec)
            print(f"{os.path.basename(path):28s} {total:8.1f} pts  {parts}")
            if args.patch and rec.get("ps_points") != total:
                rec["ps_points"] = total
                with open(path, "w") as f:
                    json.dump(rec, f, indent=2)
        return 0

    if args.cmd == "leaderboard":
        csv_path = getattr(args, "csv", None)
        recs = load_csv_records(csv_path) if csv_path else load_raw_records()
        out = os.path.join(REPO, "LEADERBOARD.md")
        with open(out, "w") as f:
            f.write(render_leaderboard(recs))
        print(f"wrote {out} ({len(recs)} records)")
        return 0


if __name__ == "__main__":
    sys.exit(main())
